#MYSQL
spring:
  datasource:
    url:
      jdbc:mysql://43.204.50.176:3306/bankerspolis_dev?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: bp_dev_user
    password: 78FMrkbVjap6XFXf
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always