
#SERVICE-CONTEXT 
server:
  port: 8003
  servlet:
    context-path: /agency-service

#EUREKA  
eureka:
  client:
    serviceUrl:
      defaultZone: http://43.204.50.176:8761/eureka/

spring:
  application:
    name: bp-agency
  profiles:
    group:
      dev: common-datasource-dev, common-redis-dev, common-aws-dev
#  profiles:
#      include:
#        - common-datasource-dev
#        - common-redis-dev
#        - common-aws-dev

  cache:
    redis:
      key-prefix: BP_AGENCY_
 
# LOGGING     
logging:
  level: 
    ROOT: INFO
    com.netflix.discovery.DiscoveryClient: ERROR
 