server:
  port: 8002
  servlet:
    context-path: /settings-service
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://43.204.50.176:8761/eureka/

spring:
  application:
    name: bp-settings
  profiles:
    group:
      dev: common-datasource-dev, common-redis-dev, common-aws-dev

  cache:
    redis:
      key-prefix: BP_MASTER_