
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8001
  servlet:
    context-path: /auth-service
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #none      
  application:
    name: AUTH-SERVICE
    
  security: #oAuth2 resource server, jwt token provider with keycloak
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dps_realm
 
#Keycloak credentials
keycloak:
  admin:
    keycloakUrl: http://localhost:8080
    adminUser: admin
    adminPassword: admin
    adminRealm: master
    adminClientId: admin-cli
    realm: dps_realm    
  client-id: dps_client
  client-secret: 5S5DrY0ldSeYfH8tgk60As3UUdosVM9f
  scope: openid, profile
  server-url: http://localhost:8080
  authorization-uri: http://localhost:8080/realms/dps_realm/protocol/openid-connect/auth
  user-info-uri: http://localhost:8080/realms/dps_realm/protocol/openid-connect/userinfo
  token-uri: http://localhost:8080/realms/dps_realm/protocol/openid-connect/token
  logout: http://localhost:8080/realms/dps_realm/protocol/openid-connect/logout
