#SERVICE-CONTEXT 
server:
  port: 8004
  servlet:
    context-path: /notification

#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: bp-notification
        
#Rabbit MQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
app:
  rabbitmq:
    exchange: dfdfdf
    queue: dfdfdf
    routingKey: dfdfdfd

# LOGGING     
logging:
  level: 
    ROOT: INFO
    com.netflix.discovery.DiscoveryClient: ERROR   