
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

server:
  port: 8004
  servlet:
    context-path: /settings-service
spring:
  application:
    name: SETTINGS-SERVICE
  
  h2:
    console:
      enabled: true
      #path: /h2-console #/h2-ui
      
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO


